### ISSUE TITLE
[BUG] Theme file not being created

### ISSUE THREAD

**Issue by agluck91** [trbnhck/warp-companion#1]
### Browser

Safari

### Bug Description

VS Code extension is not generating the warp them. 
Using warp version: v0.2022.09.13.08.15.stable_03
VS Code version: Version: 1.71.2

### Steps to Reproduce

Install extension exit and restart warp and VS Code theme does not appear in list. 

### Additional Context

This one seems straight forward.

**Comment by t128n** [comment]
I'll look into to it as soon as possible :)

**Comment by infotexture** [comment]
➕**1** Same here.

**Comment by t128n** [comment]
I just published v1.0.3 to the marketplace, which should fix this issue. If not feel free to reopen this issue :)!

https://marketplace.visualstudio.com/items?itemName=haack.warp-companion

**Comment by infotexture** [comment]
Tried again, but still no VS Code theme visible in Warp. 🤔 

- Warp `v0.2022.09.20.08.08.stable_01`
- VS Code `Version: 1.71.2`
- warp-companion: `v1.0.3`

**Comment by t128n** [comment]
Have you tried switching the theme? It should create the .yaml file, as soon as the theme is switched 🤔

**Comment by infotexture** [comment]
🙏 Thanks for the quick response.

When I switch the theme in VS Code, it opens an empty tab labeled `warp-companion-panel`, but still no evidence of any `vs` theme in Warp:

![Warp_no-vs-themes](https://user-images.githubusercontent.com/129995/192101430-0bb0db65-663b-41e6-a713-27bbcbaabacb.png)

Tried quitting & restarting both VS Code & Warp, but no luck so far.

**Comment by t128n** [comment]
Does the empty tab stay open or does it close immediately?

**Comment by bitSchleuder** [comment]
stays open

**Comment by t128n** [comment]
This bug finally should be fixed by now with the release of v1.0.4 :)

**Comment by infotexture** [comment]
With v1.0.4, the empty `warp-companion-panel` tab is gone and I get a notification in VS Code that looks promising, but still no sign of a new theme in Warp (even after restart):
 
![VS-Code_restart-Warp-toast](https://user-images.githubusercontent.com/129995/192119214-8ece4b43-1f8f-4c77-b9ec-912fd3e039f6.png)

Where should I be looking for the .yaml file?

**Comment by t128n** [comment]
Well that's interesting 🤔 The file should be located at `~/.warp/themes/vs_code.yaml`.
Might take a look at the contents, if the file exists?

**Comment by infotexture** [comment]
File is created at `~/.warp/themes/vs_code.yaml` with the following content:

```yaml
background: "#292d3e"
accent: rgba(113, 124, 180, 0.31)
foreground: "#a6accd"
details: darker
terminal_colors:
  normal:
    black: "#000000"
    red: "#ff5370"
    green: "#c3e88d"
    yellow: "#ffcb6b"
    blue: "#82aaff"
    magenta: "#c792ea"
    cyan: "#89ddff"
    white: "#ffffff"
  bright:
    black: "#676e95"
    red: "#ff5370"
    green: "#c3e88d"
    yellow: "#ffcb6b"
    blue: "#82aaff"
    magenta: "#c792ea"
    cyan: "#89ddff"
    white: "#ffffff"
```

— but for some reason, the theme is not available in the Warp theme browser <kbd>⌃</kbd> <kbd>⌘</kbd> <kbd>T</kbd>.

Checked **Security & Privacy > Privacy > Files and Folders** to see if Warp has permission to access the home folder and saw that it only had access to `Documents` & `Downloads`.

Tried granting **Full Disk Access**, but Warp still doesn't see the theme file. 🤷
